persistence:
  enabled: true
  size: 100Gi
nodeSelector:
  node-role.kubernetes.io/master: ""
service:
  type: LoadBalancer
ingress:
  enabled: true
  hosts:
    - registry.local
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 4096m
  tls:
  - hosts:
    - registry.local
