---
- name: Setup local docker registry
  hosts: all
  gather_facts: yes

  tasks:
  - name: Update /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "1.1.1.1 registry.local"
    
  - name: Copy Docker daemon config
    copy:
      src: "files/daemon.json"
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'
    become: yes
    notify: Restart docker

  handlers:
  - name: Restart docker
    service:
      name: docker
      state: restarted
    become: yes
